 CREATE DATABASE fosse_project; 
 
 CREATE TABLE Users(user_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 user_email VARCHAR(50) UNIQUE NOT NULL, password_hash TEXT NOT NULL);

 CREATE TABLE Files(file_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, user_id INTEGER NOT NULL, 
 file_name VARCHAR(50) NOT NULL, file_path TEXT NOT NULL, file_type VARCHAR(50) NOT NULL, 
 CONSTRAINT fk_user_id_for_file FOREIGN KEY (user_id) REFERENCES Users(user_id));